config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :friends
  get 'ctrl1/home'
  get 'ctrl1/help'
  get 'users/payment'
  get 'ctrl1/friends'
  get 'static/home'
  get 'sessions/new'
  get 'friends_controller/new'
  resources :users #creates appropriate routes for create, read, update, destroy(CRUD)
  resources :friends
  resources :payments
  resources :contact

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  
  delete '/logout', to: "sessions#destroy"
  root 'ctrl1#home'
  
  #search bar
  get 'friends/search'
  post 'friends/display'
  #get '/settings', to: "users#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to   :user
    validates  :name, length:  {maximum: 30}, presence:   true
    validates  :email, length:  {maximum: 30}, presence:   true
    
    def self.search(search)
	where("name Like ?", "%#{search}%") #checks if the name field matches search
    end

    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
      @friend = Friend.new
      
  end

  # GET /friends/1/edit
  def edit
  end
  
  def search
    
  end
  
  def display
    @f = Friend.search(params[:search]).order("created_at DESC")  
  end

  # POST /friends
  # POST /friends.json
  def create
   # @friend = Friend.new(friend_params)
     @friend = Friend.new
     @friend.user_id = current_user.id
     @friend.name = friend_params["name"]
     @friend.email = friend_params["email"]
     

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :user_id)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/display.html.erb
<% provide(:title, 'Search Results') %>
<h1>Searched Results</h1>



<table class="table table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <!--  User-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% for searched in @f %>
      
        <tr>
          <td><%= searched.name %></td>
          <td><%= searched.email %></td>
          <!--<td> friend.user_id </td> -->
          <td><%= link_to 'Show', searched %></td>
          <td><%= link_to 'Edit', edit_friend_path(searched) %></td>
          <td><%= link_to 'Destroy', searched, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(controller: "friends", action: "display", :method => "post", id: "search-form") do %>
<!--When the search button is clicked, the action display in the controller is called using the HTTP method post since we are sending form data! -->
<%= text_field_tag  :search, params[:search], placeholder: "Search Friends" %>  <!--this creates a text field where the user will enter what they’re searching for -->
<%= submit_tag  "Search" %>
<% end %>


<h1>Friends List</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <!--  User-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% for friend in current_user.friends %>
      
        <tr>
          <td><%= friend.name %></td>
          <td><%= friend.email %></td>
          <!--<td> friend.user_id </td> -->
          <td><%= link_to 'Show', friend %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @friend.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @friend.user_id %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>