config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :friends
  get 'ctrl1/home'
  get 'ctrl1/help'
  get 'users/payment'
  get 'ctrl1/friends'
  get 'static/home'
  get 'sessions/new'
  get 'friends_controller/new'
  resources :users #creates appropriate routes for create, read, update, destroy(CRUD)
  resources :friends
  resources :payments
  resources :contact

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  
  delete '/logout', to: "sessions#destroy"
  root 'ctrl1#home'
  
  #search bar
  get 'friends/search'
  post 'friends/display'
  #get '/settings', to: "users#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to   :sender, foreign_key: :sender_id, class_name: 'User' 
    belongs_to   :recipient, foreign_key: :recipient_id, class_name: 'User' 
    
    
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new
    @payment.amount = payment_params["amount"]
    @payment.comment = payment_params["comment"]
    @payment.recipient_id = User.find_by(name: payment_params["recipient_name"]).id
    @payment.sender_id = current_user.id
    respond_to do |format|
      if @payment.save
        
        recipient = @payment.recipient
        sender = @payment.sender
        sender.balance -=  @payment.amount
        recipient.balance += @payment.amount 
     
        sender.save
        recipient.save

        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:recipient_name, :amount, :comment)
      # params.require(:payment).permit(:recipient_name, :recipient_email, :amount, :comment, :user_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">-->
  <!--  form.label :sender_id  %> <!--form.label :recipient_name-->
  <!--  form.text_area :sender_id  %>   <!-- #form.text_area :recipient_name-->
  <!--</div>-->

  <h1>  Welcome, <%=  current_user.name %> </h1>
  
  <div class="field">
    <%= form.label :recipient %>
    <%= form.text_area :recipient_name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <!--<div class="field">-->
  <!-- form.label :user_id -->  
  <!--   form.number_field :user_id-->
  <!--</div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<body>h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>
</body>

app/views/payments/index.html.erb
<body>
  <p id="notice"><%= notice %></p>

<h2>Payments Made</h2>

<table class="table table-dark">
  <thead>
    <tr>
      <th>Sender name   </th>
      <th>Recipient name   </th>
      <th>Recipient email   </th>
      <th>Amount   </th>
      <th>Comment   </th>
      <th>User  </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <%  if payment.sender.name==current_user.name %> 
        <tr>
          <td><%= payment.sender.name %></td>
          <td><%= payment.recipient.name %></td>
          <td><%= payment.recipient.email %></td>
          <td>$<%= payment.amount %></td>
          <td><%= payment.comment %></td>
        
          <td><%= link_to 'Show', payment %></td>
          <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
          <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h2>Payments recieved</h2>

<table class="table table-dark">
  <thead>
    <tr>
      <th>Sender name   </th>
      <th>Recipient name   </th>
      <th>Recipient email   </th>
      <th>Amount   </th>
      <th>Comment   </th>
      <th>User  </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <%  if payment.recipient.name==current_user.name %> 
        <tr>
          <td><%= payment.sender.name %></td>
          <td><%= payment.recipient.name %></td>
          <td><%= payment.recipient.email %></td>
          <td>$<%= payment.amount %></td>
          <td><%= payment.comment %></td>
        
          <td><%= link_to 'Show', payment %></td>
          <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
          <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>
</body>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipient name:</strong>
  <%= @payment.recipient.name %>
</p>

<p>
  <strong>Email:  </strong>
  <%= @payment.recipient.email %>
</p>

<p>
  <strong>Amount:  </strong>
  $<%= @payment.amount %>
</p>

<p>
  <strong>Comment:  </strong>
  <%= @payment.comment %>
</p>



<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>