config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :friends
  get 'ctrl1/home'
  get 'ctrl1/help'
  get 'users/payment'
  get 'ctrl1/friends'
  get 'static/home'
  get 'sessions/new'
  get 'friends_controller/new'
  resources :users #creates appropriate routes for create, read, update, destroy(CRUD)
  resources :friends
  resources :payments
  resources :contact

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  
  delete '/logout', to: "sessions#destroy"
  root 'ctrl1#home'
  
  #search bar
  get 'friends/search'
  post 'friends/display'
  #get '/settings', to: "users#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class= 'footer'>

<nav>
<ul>
   <li><%= link_to 'About', '#' %></li>
   <li><%= link_to 'Contact', '#' %></li>
   <li><a href= 'http://www.depauw.edu'> DePauw University</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <h1 class="title homebody"> Liquidate</h1>
        <nav>
          <ul class="nav navbar-nav navbar-right" style="background: linear-gradient(160deg, #9200db, #300);">
            <li><%= link_to "Home", controller: 'ctrl1', action: 'home' %></li>
            <li><%= link_to "Contact Us", contacts_path %></li>
            

            <% if logged_in? %>
               <li><%= link_to "Make Payment", payments_path %></li>
               <li><%= link_to "Friends", friends_path %></li>
               <li><%= link_to 'Users', controller: 'users', action: 'index' %> <li/> <!-- users_path-->
               <li class= "dropdown">
               <a href= "#" class= "dropdown-toggle" data-toggle= "dropdown"> Account <b class= "caret"></b></a>
               <ul class="dropdown-menu">
                 <li><%= link_to 'Profile', current_user %></li>
	             <li><%= link_to "Settings", edit_user_path(current_user) %></li>  <!-- edit_user_path(current_user)-->
                 <li class= "divider"></li>
                 <li><%= link_to "Log out", logout_path, method: :delete %></li>
               </ul>
               </li>
               <% else %>
                  <li><%= link_to "Log in", login_path %></li>
               <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <br/><br/><br/><br/><br/>
    <%= yield %>
    
    <% flash.each do |message_type, message| %>  
      <div class="alert alert-<%= message_type %>"><%= message %></div> 
    <% end %>

    
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>